name: get-voting-outcome
author: tfadeyi
description: 'Add a simple voting mechanism through github discussions'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  platform:
    description: 'The platform where the voting will take place'
    required: false
    default: 'github'
  instance:
    description: 'The instance unique identifier'
    required: false
    default: "${{ github.run_id }}"
  # github specific flags
  token:
    description: 'The github auth token'
    required: false
    default: "${{ github.token }}"
  labels:
    description: 'The github issue label name to monitor, i.e: election'
    required: true
    default: 'generic'
  owner:
    description: 'The name of the repository owner'
    required: false
    default: "${{ github.repository_owner }}"
  repository:
    description: 'The name of the repository'
    required: false
    default: "${{ github.repository }}"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/tfadeyi/governance'
  args:
    - "vote"
    - "monitoring"
    - "--platform"
    - ${{ inputs.platform }}
    - "--instance"
    - ${{ inputs.instance }}
    - "--github.labels"
    - ${{ inputs.labels }}
    - "--github.repository"
    - ${{ inputs.repository }}
    - "--github.repository-owner"
    - ${{ inputs.owner }}
    - "--github.token"
    - ${{ inputs.token }}
